#!/usr/bin/env bash

#SBATCH --time=00:10:00
#SBATCH --mem=5G
#SBATCH --cpus-per-task=4
#SBATCH --job-name=meryl
#SBATCH --mail-user=yannick.jauslin@students.unibe.ch
#SBATCH --mail-type=end
#SBATCH --output=/data/users/yjauslin/output_meryl_%j.o
#SBATCH --error=/data/users/yjauslin/error_meryl_%j.e
#SBATCH --partition=pibu_el8

WORK_DIR=/data/users/${USER}/assembly_annotation_course

CONTAINER="/containers/apptainer/merqury_1.3.sif"

READS="${WORK_DIR}/Hiroshima/ERR11437318.fastq.gz"

OUT_DIR=${WORK_DIR}/mercury

mkdir $OUT_DIR

apptainer exec --bind ${WORK_DIR} ${CONTAINER} meryl k=18 count \
  ${READS} output ${OUT_DIR}/reads.meryl     